server:
  port: 8080

spring:
  application:
    name: clean-arch
  data:
    mongodb:
      uri: mongodb://localhost:27017/clean-arch
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1
    consumer:
      group-id: clean-arch-consumer
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      auto-offset-reset: earliest
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher